export declare enum ContextType {
    ELEMENT_TYPE = "elementType",
    ID = "id",
    TAG_NAME = "tagName",
    CLASS_NAME = "className",
    CORE_NODE_CLASS_NAME = "coreNodeClassName",
    INNER_TEXT = "innerText",
    INNER_ELEMENT_TEXT = "innerElementText",
    PURPOSE = "purpose",
    SIZE_CATEGORY = "sizeCategory",
    UNDEFINED = "undef.",
    BUTTON_TYPE = "buttonType",
    TABLE_ROW_TYPE = "tableRowType",
    TABLE_ROW_INDEX = "tableRowIndex",
    TABLE_COLUMN_INDEX = "tableColumnIndex",
    TABLE_COLUMN_TYPE = "tableColumnType",
    LABEL = "label",
    SUB_HEADING = "subHeading",
    INPUT_NAME = "inputName",
    INPUT_TYPE = "inputType",
    PLACEHOLDER = "placeholder",
    SELECT_OPTION = "selectOption",
    ACCEPT_FILE_TYPES = "acceptFileTypes",
    LINK_HREF = "linkHref",
    IS_RECURRING = "isRecurring"
}
