export declare enum ElementType {
    RADIO_BUTTONS_GROUP = "RadioButtonGroup",
    RADIO_BUTTON = "RadioButton",
    CHECKBOX = "Checkbox",
    TABLE_ROW = "TableRow",
    TABLE_COLUMN = "TableColumn",
    TEXT = "Text",
    ROOT = "Root",
    HEADING = "Heading",
    HEADER = "Header",
    BUTTON = "Button",
    MENU = "Menu",
    BOX = "Box",
    FORM = "Form",
    TABLE = "Table",
    INPUT = "Input",
    RECURRING_BOX = "RecurringBox",
    LABEL = "Label",
    UNDEFINED = "Undefined",
    SELECT = "Select",
    A = "a",
    INVALID = "Invalid",
    NAVIGATION = "Navigation",
    MAYBESELECT = "MayBeSelect"
}
