/**
 * check auto-generated selectors
 * @param {String} val
 * @return {boolean} is auto-generated
 */
export declare function isAutogenerated(className: string): boolean;
export declare function filterAutogenClasses(classNames: string[]): string[];
