
var autogenRegexps = [
  /\d{1,}/,
  /^ember\d+/,
  /^[0-9_-]+$/,
  /^_\d{2,}/,
  /([a-f_-]*[0-9_-]){6,}/i,
  /preflight-highlight/,
  /select2-/,
  /^v-/,
  /^data-v-/,
  /hover/,
  /activ|focus|hydrated|solid|button|black|touch|stack|label|pristine|valid|placeholder|input|dirty|selected|collaps|show|hide|visibl|highlight/,
  /open/,
  /^item-|^blue-|^in-|^has/,
  /^md$/,
  /^ng-/,
  /\.|\]|\[|\{|\}|:|\)|\(|\*|\$/,
  /([A-Z].[A-Z])|(^[a-z].*[A-Z])|(\-[0-9])|([qwrtpsdfghjklzxcvbnm]{4,})|([a-z]{2}[A-Z]{1}.{2})|([A-Z]{2,})|([0-9]{2,})|([a-z].*[0-9].*)/,
];

/**
 * check auto-generated selectors
 * @param {String} val
 * @return {boolean} is auto-generated
 */
export function autogenCheck(val) {
  if (!val) {
    return false;
  }
  var autogenerated = autogenRegexps.find(function(reg) {
    return reg.test(val);
  });
  return !!autogenerated;
}
